import type { BoostCard } from './types';

export const boostCards: BoostCard[] = [
  {
    id: '1',
    name: 'Bronze Booster',
    description: 'Small boost to your progression and earnings',
    xpBoost: 25,
    coinBoost: 10,
    feeReturnBoost: 85,
    duration: '7 days',
    rarity: 'common',
    price: 500,
    currency: 'coins',
    image: '🛡️',
    featured: false,
  },
  {
    id: '2',
    name: 'Silver Enhancer',
    description: 'Enhanced progression for dedicated players',
    xpBoost: 50,
    coinBoost: 20,
    feeReturnBoost: 90,
    duration: '30 days',
    rarity: 'rare',
    price: 2000,
    currency: 'coins',
    image: '⚡',
    featured: true,
  },
  {
    id: '3',
    name: 'Gold Dominator',
    description: 'Maximum progression speed and rewards',
    xpBoost: 75,
    coinBoost: 35,
    feeReturnBoost: 95,
    duration: '30 days',
    rarity: 'epic',
    price: 8000,
    currency: 'coins',
    image: '👑',
    featured: true,
  },
  {
    id: '4',
    name: 'Platinum God',
    description: 'Ultimate progression and exclusive benefits',
    xpBoost: 100,
    coinBoost: 50,
    feeReturnBoost: 98,
    duration: 'permanent',
    rarity: 'legendary',
    price: 25000,
    currency: 'coins',
    image: '💎',
    featured: true,
  },
];

export const rarityColors = {
  common: 'text-gray-400 bg-gray-400/20',
  rare: 'text-blue-400 bg-blue-400/20',
  epic: 'text-purple-400 bg-purple-400/20',
  legendary: 'text-yellow-400 bg-yellow-400/20',
};
