export const PROFILE_DATA: Record<string, any> = {
  '1': {
    id: '1',
    username: 'ProGamer99',
    avatar: 'PG',
    level: 18,
    experience: 1250,
    nextLevelExp: 2000,
    joinDate: '2023-03-15',
    status: 'away',
    bio: 'Competitive strategy gamer with a passion for outsmarting opponents. Always up for a challenge! 🎮',
    country: 'United States',
    favoriteGame: 'Space Warriors',
    title: 'Grandmaster',
    clan: 'Dragon Slayers',
    rank: 'Top 100',
    isFriend: true,
    isCurrentUser: false,
  },
  '2': {
    id: '2',
    username: 'ChessMaster',
    avatar: 'CM',
    level: 12,
    experience: 800,
    nextLevelExp: 1000,
    joinDate: '2023-06-20',
    status: 'online',
    bio: 'Chess enthusiast and puzzle solver. Love games that make you think! ♟️',
    country: 'Canada',
    favoriteGame: 'Animal Chess',
    title: 'Strategist',
    clan: 'Mind Benders',
    rank: 'Top 500',
    isFriend: false,
    isCurrentUser: false,
  },
  current: {
    id: 'current',
    username: 'CosmicPlayer',
    avatar: 'CP',
    level: 15,
    experience: 1250,
    nextLevelExp: 2000,
    joinDate: '2023-01-10',
    status: 'online',
    bio: 'Passionate gamer exploring all genres. Always looking for the next great challenge! 🌟',
    country: 'United Kingdom',
    favoriteGame: '5 Lines Sheep Fight',
    title: 'Champion',
    clan: 'Star Guardians',
    rank: 'Top 250',
    isCurrentUser: true,
  },
};

export const PROFILE_STATS: Record<string, any> = {
  '1': {
    totalGames: 342,
    wins: 198,
    losses: 144,
    winRate: 57.9,
    currentStreak: 3,
    bestStreak: 12,
    averageGameTime: '15:23',
    favoriteGame: 'Space Warriors',
    totalPlayTime: '87h 32m',
    tournamentsWon: 8,
    maxScore: 24500,
  },
  '2': {
    totalGames: 187,
    wins: 112,
    losses: 75,
    winRate: 59.9,
    currentStreak: 5,
    bestStreak: 8,
    averageGameTime: '12:45',
    favoriteGame: 'Animal Chess',
    totalPlayTime: '42h 15m',
    tournamentsWon: 3,
    maxScore: 18700,
  },
  current: {
    totalGames: 256,
    wins: 145,
    losses: 111,
    winRate: 56.6,
    currentStreak: 2,
    bestStreak: 7,
    averageGameTime: '14:30',
    favoriteGame: '5 Lines Sheep Fight',
    totalPlayTime: '62h 48m',
    tournamentsWon: 5,
    maxScore: 21500,
  },
};

export const PROFILE_GAMES: Record<string, any[]> = {
  '1': [
    {
      id: 1,
      name: 'Space Warriors',
      icon: 'rocket',
      playCount: 124,
      winRate: 62.1,
      lastPlayed: '2024-01-15',
      totalTime: '32h 15m',
      bestScore: 24500,
    },
    {
      id: 2,
      name: 'Dragon Arena',
      icon: 'dragon',
      playCount: 87,
      winRate: 54.0,
      lastPlayed: '2024-01-14',
      totalTime: '21h 30m',
      bestScore: 18700,
    },
    {
      id: 3,
      name: '5 Lines Sheep Fight',
      icon: 'lines-leaning',
      playCount: 65,
      winRate: 58.5,
      lastPlayed: '2024-01-13',
      totalTime: '16h 45m',
      bestScore: 15600,
    },
  ],
  current: [
    {
      id: 1,
      name: '5 Lines Sheep Fight',
      icon: 'lines-leaning',
      playCount: 89,
      winRate: 58.4,
      lastPlayed: '2024-01-15',
      totalTime: '22h 15m',
      bestScore: 21500,
    },
    {
      id: 2,
      name: 'Animal Chess',
      icon: 'chess',
      playCount: 67,
      winRate: 55.2,
      lastPlayed: '2024-01-14',
      totalTime: '14h 30m',
      bestScore: 18900,
    },
    {
      id: 3,
      name: 'Space Warriors',
      icon: 'rocket',
      playCount: 54,
      winRate: 52.8,
      lastPlayed: '2024-01-13',
      totalTime: '13h 45m',
      bestScore: 16700,
    },
  ],
};

export const PROFILE_ACHIEVEMENTS: Record<string, any[]> = {
  '1': [
    {
      id: 1,
      name: 'First Victory',
      icon: 'trophy',
      description: 'Win your first game',
      unlockedAt: '2023-03-16',
      rarity: 'common',
      category: 'gaming',
    },
    {
      id: 2,
      name: 'Game Collector',
      icon: 'gamepad',
      description: 'Play 10 different games',
      unlockedAt: '2023-04-20',
      rarity: 'common',
      category: 'collection',
    },
    {
      id: 3,
      name: 'Win Streak',
      icon: 'fire',
      description: 'Win 5 games in a row',
      unlockedAt: '2023-05-15',
      rarity: 'rare',
      category: 'skill',
    },
    {
      id: 4,
      name: 'Master Strategist',
      icon: 'brain',
      description: 'Win 100 strategy games',
      unlockedAt: '2023-08-10',
      rarity: 'epic',
      category: 'skill',
    },
  ],
  current: [
    {
      id: 1,
      name: 'First Victory',
      icon: 'trophy',
      description: 'Win your first game',
      unlockedAt: '2023-01-11',
      rarity: 'common',
      category: 'gaming',
    },
    {
      id: 2,
      name: 'Game Collector',
      icon: 'gamepad',
      description: 'Play 10 different games',
      unlockedAt: '2023-02-15',
      rarity: 'common',
      category: 'collection',
    },
    {
      id: 3,
      name: 'Social Butterfly',
      icon: 'users',
      description: 'Add 10 friends',
      unlockedAt: '2023-03-20',
      rarity: 'common',
      category: 'social',
    },
    {
      id: 4,
      name: 'Win Streak',
      icon: 'fire',
      description: 'Win 5 games in a row',
      unlockedAt: '2023-04-25',
      rarity: 'rare',
      category: 'skill',
    },
  ],
};

export const PROFILE_BADGES: Record<string, any[]> = {
  '1': [
    {
      id: 1,
      name: 'Season 1 Champion',
      icon: 'crown',
      description: 'Top player in Season 1',
      unlockedAt: '2023-12-01',
      type: 'seasonal',
    },
    {
      id: 2,
      name: 'Halloween Event',
      icon: 'ghost',
      description: 'Completed Halloween challenges',
      unlockedAt: '2023-10-31',
      type: 'event',
    },
    {
      id: 3,
      name: 'Elite Rank',
      icon: 'star',
      description: 'Reached Elite ranking',
      unlockedAt: '2023-09-15',
      type: 'rank',
    },
  ],
  current: [
    {
      id: 1,
      name: 'Season 2 Participant',
      icon: 'medal',
      description: 'Active in Season 2',
      unlockedAt: '2024-01-01',
      type: 'seasonal',
    },
    {
      id: 2,
      name: 'Winter Warrior',
      icon: 'snowflake',
      description: 'Winter event completion',
      unlockedAt: '2023-12-25',
      type: 'event',
    },
    {
      id: 3,
      name: 'Rising Star',
      icon: 'rocket',
      description: 'Fast level progression',
      unlockedAt: '2023-11-20',
      type: 'rank',
    },
  ],
};

export const PROFILE_TIMELINE: Record<string, any[]> = {
  '1': [
    {
      id: 1,
      type: 'level_up',
      title: 'Reached Level 18',
      description: 'Advanced to Grandmaster rank',
      date: '2024-01-15',
      icon: 'level-up-alt',
    },
    {
      id: 2,
      type: 'game_played',
      title: 'Won Space Warriors',
      description: 'Victory with 24,500 points',
      date: '2024-01-15',
      icon: 'gamepad',
      game: 'Space Warriors',
    },
    {
      id: 3,
      type: 'achievement',
      title: 'Unlocked Master Strategist',
      description: 'Won 100 strategy games',
      date: '2024-01-14',
      icon: 'trophy',
    },
    {
      id: 4,
      type: 'tournament',
      title: 'Tournament Victory',
      description: 'Won weekly tournament',
      date: '2024-01-12',
      icon: 'award',
    },
  ],
  current: [
    {
      id: 1,
      type: 'level_up',
      title: 'Reached Level 15',
      description: 'Advanced to Champion rank',
      date: '2024-01-15',
      icon: 'level-up-alt',
    },
    {
      id: 2,
      type: 'game_played',
      title: 'Played 5 Lines Sheep Fight',
      description: 'New high score: 21,500',
      date: '2024-01-15',
      icon: 'gamepad',
      game: '5 Lines Sheep Fight',
    },
    {
      id: 3,
      type: 'friend_added',
      title: 'Added ProGamer99',
      description: 'Now friends with ProGamer99',
      date: '2024-01-14',
      icon: 'user-plus',
    },
    {
      id: 4,
      type: 'achievement',
      title: 'Unlocked Win Streak',
      description: 'Won 5 games in a row',
      date: '2024-01-13',
      icon: 'fire',
    },
  ],
};
