import type { LeaderboardEntry } from './LeaderboardTable/types';
import type { TimeFrameStats } from './types';

export const leaderboardData: LeaderboardEntry[] = [
  {
    id: '1',
    rank: 1,
    playerName: 'CometMaster',
    score: 9850,
    gamesPlayed: 142,
    winRate: 78,
    level: 45,
    avatar: '👑',
    country: 'US',
    favoriteGame: 'Space Raiders',
    lastActive: '2 min ago',
    isOnline: true,
    isCurrentUser: false,
    achievements: ['top_rank', 'win_streak_10', 'early_adopter'],
  },
  {
    id: '2',
    rank: 2,
    playerName: 'StarChaser',
    score: 8765,
    gamesPlayed: 118,
    winRate: 72,
    level: 42,
    avatar: '🚀',
    country: 'UK',
    favoriteGame: 'Galaxy Quest',
    lastActive: '5 min ago',
    isOnline: true,
    isCurrentUser: false,
    achievements: ['win_streak_5', 'dedicated_player'],
  },
  {
    id: '3',
    rank: 3,
    playerName: 'GalaxyHunter',
    score: 7654,
    gamesPlayed: 95,
    winRate: 68,
    level: 38,
    avatar: '🛸',
    country: 'DE',
    favoriteGame: 'Cosmic Battle',
    lastActive: '1 hour ago',
    isOnline: false,
    isCurrentUser: false,
    achievements: ['fast_learner', 'first_win'],
  },
  {
    id: '4',
    rank: 4,
    playerName: 'NeptuneGamer',
    score: 6543,
    gamesPlayed: 87,
    winRate: 65,
    level: 35,
    avatar: '🌌',
    country: 'CA',
    favoriteGame: 'Ocean Explorer',
    lastActive: '30 min ago',
    isOnline: true,
    isCurrentUser: false,
    achievements: ['consistent_player'],
  },
  {
    id: '5',
    rank: 5,
    playerName: 'CosmicPlayer',
    score: 5432,
    gamesPlayed: 76,
    winRate: 62,
    level: 32,
    avatar: '⭐',
    country: 'AU',
    favoriteGame: 'Star Fighter',
    lastActive: '2 hours ago',
    isOnline: false,
    isCurrentUser: false,
    achievements: ['new_comer'],
  },
  {
    id: '6',
    rank: 8,
    playerName: 'You',
    score: 4321,
    gamesPlayed: 65,
    winRate: 58,
    level: 28,
    avatar: '😊',
    country: 'US',
    favoriteGame: 'Space Raiders',
    lastActive: 'Now',
    isOnline: true,
    isCurrentUser: true,
    achievements: ['rising_star', 'first_win'],
  },
  {
    id: '7',
    rank: 6,
    playerName: 'MeteorStrike',
    score: 4987,
    gamesPlayed: 89,
    winRate: 61,
    level: 31,
    avatar: '☄️',
    country: 'JP',
    favoriteGame: 'Asteroid Miner',
    lastActive: '15 min ago',
    isOnline: true,
    isCurrentUser: false,
    achievements: ['mining_expert'],
  },
  {
    id: '8',
    rank: 7,
    playerName: 'OrbitRunner',
    score: 4567,
    gamesPlayed: 72,
    winRate: 59,
    level: 29,
    avatar: '🛰️',
    country: 'FR',
    favoriteGame: 'Space Race',
    lastActive: '45 min ago',
    isOnline: false,
    isCurrentUser: false,
    achievements: ['speed_demon'],
  },
];

export const timeFrameStats: TimeFrameStats[] = [
  { label: 'Total Players', value: '15.2K', change: +12 },
  { label: 'Active Today', value: '3.8K', change: +5 },
  { label: 'Games Played', value: '45.7K', change: +18 },
  { label: 'Avg. Score', value: '2.4K', change: +3 },
];

export const achievementIcons: Record<string, string> = {
  top_rank: 'crown',
  win_streak_10: 'fire',
  win_streak_5: 'bolt',
  early_adopter: 'rocket',
  dedicated_player: 'heart',
  fast_learner: 'graduation-cap',
  first_win: 'trophy',
  consistent_player: 'chart-line',
  new_comer: 'seedling',
  rising_star: 'star',
  mining_expert: 'gem',
  speed_demon: 'running',
};
