import type { Game, GameCategory } from './types';

export const GAME_CATEGORIES: GameCategory[] = [
  { id: 'all', name: 'All Games', icon: 'gamepad', count: 24 },
  { id: 'strategy', name: 'Strategy', icon: 'chess', count: 8 },
  { id: 'action', name: 'Action', icon: 'fighter-jet', count: 6 },
  { id: 'puzzle', name: 'Puzzle', icon: 'puzzle-piece', count: 5 },
  { id: 'card', name: 'Card Games', icon: 'heart', count: 3 },
  { id: 'adventure', name: 'Adventure', icon: 'map', count: 2 },
];

export const GAMES: Game[] = [
  {
    id: 1,
    name: '5 Lines Sheep Fight',
    description:
      'Strategic card battle with cute sheep characters in a 5-line formation. Outsmart your opponents!',
    players: '2-4 Players',
    online: '1.2K',
    icon: 'sheep',
    color: 'from-green-500 to-emerald-500',
    gradient: 'bg-gradient-to-r from-green-500 to-emerald-500',
    category: 'strategy',
    rating: 4.8,
    tags: ['Card', 'Strategy', 'Multiplayer'],
    isFeatured: true,
    isNew: false,
  },
  {
    id: 2,
    name: 'Animal Chess',
    description:
      'Classic chess reimagined with animal-themed pieces. Strategic gameplay for all skill levels.',
    players: '2 Players',
    online: '856',
    icon: 'chess',
    color: 'from-yellow-500 to-orange-500',
    gradient: 'bg-gradient-to-r from-yellow-500 to-orange-500',
    category: 'strategy',
    rating: 4.6,
    tags: ['Chess', 'Strategy', '2 Player'],
    isFeatured: true,
    isNew: true,
  },
  {
    id: 3,
    name: 'Space Warriors',
    description:
      'Epic space battle with real-time strategy. Build your fleet and conquer the galaxy!',
    players: '2-8 Players',
    online: '2.4K',
    icon: 'rocket',
    color: 'from-blue-500 to-purple-500',
    gradient: 'bg-gradient-to-r from-blue-500 to-purple-500',
    category: 'action',
    rating: 4.9,
    tags: ['Space', 'Action', 'Real-time'],
    isFeatured: true,
    isNew: false,
  },
  {
    id: 4,
    name: 'Dragon Arena',
    description:
      'Fantasy battle arena with magical creatures. Team up and defeat powerful bosses!',
    players: '3-5 Players',
    online: '1.8K',
    icon: 'dragon',
    color: 'from-red-500 to-pink-500',
    gradient: 'bg-gradient-to-r from-red-500 to-pink-500',
    category: 'adventure',
    rating: 4.7,
    tags: ['Fantasy', 'RPG', 'Co-op'],
    isFeatured: false,
    isNew: true,
  },
  {
    id: 5,
    name: 'Quantum Puzzle',
    description:
      'Mind-bending puzzles that challenge your logic and spatial reasoning skills.',
    players: '1-2 Players',
    online: '623',
    icon: 'puzzle-piece',
    color: 'from-indigo-500 to-blue-500',
    gradient: 'bg-gradient-to-r from-indigo-500 to-blue-500',
    category: 'puzzle',
    rating: 4.5,
    tags: ['Puzzle', 'Logic', 'Brain Teaser'],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 6,
    name: 'Royal Cards',
    description:
      'Compete in epic card battles with magical powers and special abilities.',
    players: '2-4 Players',
    online: '945',
    icon: 'heart',
    color: 'from-pink-500 to-rose-500',
    gradient: 'bg-gradient-to-r from-pink-500 to-rose-500',
    category: 'card',
    rating: 4.4,
    tags: ['Cards', 'Magic', 'Tactical'],
    isFeatured: false,
    isNew: true,
  },
  {
    id: 7,
    name: 'Cyber Racing',
    description:
      'High-speed racing through futuristic cities with customizable vehicles.',
    players: '1-8 Players',
    online: '1.1K',
    icon: 'car',
    color: 'from-cyan-500 to-blue-500',
    gradient: 'bg-gradient-to-r from-cyan-500 to-blue-500',
    category: 'action',
    rating: 4.6,
    tags: ['Racing', 'Action', 'Multiplayer'],
    isFeatured: false,
    isNew: false,
  },
  {
    id: 8,
    name: 'Mystic Quest',
    description:
      'Embark on an epic adventure through magical lands and ancient ruins.',
    players: '1-4 Players',
    online: '734',
    icon: 'map',
    color: 'from-purple-500 to-indigo-500',
    gradient: 'bg-gradient-to-r from-purple-500 to-indigo-500',
    category: 'adventure',
    rating: 4.7,
    tags: ['Adventure', 'RPG', 'Story'],
    isFeatured: false,
    isNew: false,
  },
];

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Most Popular' },
  { value: 'newest', label: 'Newest First' },
  { value: 'rating', label: 'Highest Rated' },
  { value: 'name', label: 'Alphabetical' },
];
